services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - 5173:5173
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
